version: '2'
services:
  curlai:
    image: a6b8/curlai-discover:0.2
    ports:
        - "80:80"
    environment:
      DEBUG_FILE : /run/secrets/data-curlai-com-1569801380-debug
      MULTIPLICATOR_FILE : /run/secrets/data-curlai-com-1569801380-multiplicator
    secrets:
    - data-curlai-com-1569801380-debug
    - data-curlai-com-1569801380-multiplicator
secrets:
  data-curlai-com-1569801380-debug:
    external: 'true'
  data-curlai-com-1569801380-multiplicator:
    external: 'true'